local:
  safe:
  block:

allow:
  - name: Anudeep whitelist
    repository: https://github.com/anudeepND/whitelist
    sources:
      - https://raw.githubusercontent.com/anudeepND/whitelist/refs/heads/master/domains/whitelist.txt
    type: domains

deny:
  - name: Steven Black
    repository: https://github.com/StevenBlack/hosts
    sources:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
    type: hosts

  - name: Peter Lowe
    url: https://pgl.yoyo.org/adservers/
    sources:
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
    type: hosts

  - name: Disconnect
    url: https://disconnect.me
    sources:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    type: domains

  - name: Matomo
    url: https://matomo.org/
    repository: https://github.com/matomo-org/referrer-spam-list
    sources:
      - https://raw.githubusercontent.com/matomo-org/referrer-spam-list/refs/heads/master/spammers.txt
    type: domains

  - name: Phishing Army
    url: https://phishing.army/
    sources:
      - https://phishing.army/download/phishing_army_blocklist.txt
    type: domains
